### ISSUE TITLE
Remove extra page before executive summary

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#17]
In email from OMNI: 

> When we knit documents there is a blank page before the executive summary and at the end of the report, can these be removed?

Can you check this out please?

**Comment by tvroylandt** [comment]
I have a blank page after the executive summary : 
![image](https://user-images.githubusercontent.com/28248895/87232263-ca63e100-c3bd-11ea-9ede-488b97eec624.png)

Is that this one that they want to delete ?

I also have the one after the end of the report.

**Comment by tvroylandt** [comment]
This one was complicated. This was caused by a `page:chapter` in some CSS due to : https://www.pagedjs.org/documentation/08-named-pages/

I solved it by changing the properties as from https://github.com/rstudio/pagedown/issues/145

**Comment by dgkeyes** [comment]
Perfect, thanks!
