### ISSUE TITLE
Make creation of new report not create extra files etc

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#22]
From @OskaratOmni:

> currently, if one uses a report template, additional materials are generated and stored in same directory as the file (e.g., skeleton.html). Can these either be routed to a folder (called ‘skeletons'?) or not generated at all if they are not needed.

> likewise, when one makes a new document a new folder is made within the root folder. This can be inefficient because now the document is one level below the root folder and either other adjustments need to be made (to paths in the scripts, etc) or some cleanup and tidying has to happen. Ideally, use of a template would not change the folder hierarchy.

**Comment by tvroylandt** [comment]
This are two issues in fact.

For the first one :

+ I wrapped everything possible in a custom format (which is now my standard way to do)
+ Put the materials in `inst/assets`
+ Plus did some cleaning

Note that this will still generate an `images/` folder if you use the `use_image` option on the tables (TRUE by default).

I have an uncertainty about this still working with `lof` since Pandoc/`pagedown` version has changed in three years.

**Comment by tvroylandt** [comment]
This also solved the second issue by the same way. This was an odd behaviour of RStudio due to having many files in the template : https://github.com/rstudio/rstudio/issues/3331

**Comment by OskaratOmni** [comment]
Thank you Thomas and thank you David,
I look forward to learning from both of you as we revamp this package.

Thomas, what are your thoughts on using bookdown formats for cases where we are knitting to html or Word? I’m not sure of the advantages of bookdown compared to pagedown but for random reasons have used bookdown much more than pagedown. I like that it makes Latex-like functionality in figure numbering very easy. It seems that pagedown is better for pdfs, especially if the formatting is complex, but I don’t have a strong view either way of course.

I need to get you both the updated OMNI data-viz guidelines (these include fonts and color templates). I am meeting with someone later today about this.

More soon –
Best
Oskar

Oskar Burger (he/him)
Senior Research Manager, OMNI Institute
(720) 712-7229
www.omni.org<http://www.omni.org/>

**Comment by tvroylandt** [comment]
Hi Oskar,

In fact, `pagedown`::html_paged()` is built on top of `bookdown::html_document2()`. We then print it to pdf using the Chrome PDF printer.

I would definitely recommend `bookdown` when knitting to html or Word.

**Comment by dgkeyes** [comment]
@tvroylandt can you please share instructions with @OskaratOmni on how he can install the `dev` branch of the package and test it out?

**Comment by OskaratOmni** [comment]
This sounds great Thomas, thanks!
I am suddenly slammed with project work but I will make sure I keep some time to move the package forward soon.

We are compiling the data-viz standards shortly. They are dispersed across many documents and need to be consolidated.

Thanks!

Oskar Burger (he/him)
Senior Research Manager, OMNI Institute
(720) 712-7229
www.omni.org<http://www.omni.org/>
