### ISSUE TITLE
Qualtrics function

### ISSUE THREAD

**Issue by tvroylandt** [rfortherestofus/omni#24]
Wrap connexion to Qualtrics in a function (make update of API key possible) + template for analysis

**Comment by dgkeyes** [comment]
Just recording some thoughts here. We're basically just writing some light wrappers around functions in the qualtRics package.

- We need a way to have people save their credentials. It would basically be a wrapper around the `qualtrics_api_credentials()` function. Is there a way we could have it write the system variable `OMNI_QUALTRICS_API_KEY` and `OMNI_QUALTRICS_BASE_URL`? This may just be for me, but I work with multiple clients who use Qualtrics so I can't save as `QUALTRICS_API_KEY` and `QUALTRICS_BASE_URL`. It could be a good way to ensure that people are using the function we create too.
- We need a way for people to be able to see all of the survey names and ids. This is basically just the `all_surveys()` function.
- We need a wrapper around the `fetch_surveys()` function. I'd also like people to be able to get the survey by its id or by its name. Also, if there are defaults that OMNI uses with the `fetch_survey()` function (e.g. force_request = TRUE), we should set those by default.

**Comment by tvroylandt** [comment]
On this, I defined two functions :

- `omni::qualtromni_register(people_name, api_key, base_url)` will write vars to .Renviron with a people/org name -> run only once
- `omni::qualtromni_connect(people_name)` will read this vars and connect -> run at each session

**Comment by tvroylandt** [comment]
I also add two wrappers :

- `omni::qualtromni_list_survey()` which is basically `qualtRics::all_surveys()`
- `omni::qualtromni_get_survey(survey_id_name)` where you can fetch survey by name or ID

**Comment by dgkeyes** [comment]
Thanks. I just don't think I quite understand what's going on. [Quick video with feedback](https://show.rfor.us/yvyLNJ5q). Do you mind explaining this a bit more?

**Comment by tvroylandt** [comment]
Ok to change the name. Qualtromni was kind too much of a joke I believe.

To explain :

- `qualtrics_register` will write variable in the .Renviron base on `people_name` (we can change the parameter name). If you have multiples templates you can register many variables. This has to be run once 
-  `qualtrics_connect` will get this variable based on the name and load them into your env so that the `qualtRics` package can use them

**Comment by dgkeyes** [comment]
Ah yes, that makes sense! I made one small change, switching the `people_name` argument to `organization_name` and setting the default to OMNI. 

@OskaratOmni we have this set of functions ready for you. [Here's a quick video explanation](https://show.rfor.us/sQSC2kCK). Let us know what you think!
