### ISSUE TITLE
Remove registering of fonts

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#25]
@tvroylandt let me know what you think about [this](https://show.rfor.us/h5wSD7rk).

**Comment by tvroylandt** [comment]
I'm in favour of just removing the message. If it works, why change it ?

Otherwise we would have to do a complete check of the rest of the package to be sure we didn't broke anything.

**Comment by dgkeyes** [comment]
That sounds good to me. Just did it.
