### ISSUE TITLE
[R-32] group col to omni table

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#28]
Hey @dgkeyes  and @tvroylandt 
I'm using and appreciating the slidy template and in so doing I re-made a talk I'd made the other day, just to get acquainted with the template. One thing I've grown accustomed to using is the gt() package for html formatted tables. 
I really like how easy it is to add a grouping variable to a table. 
e.g., mtcars %>% select(mpg, am, gear, disp) %>% gt(groupname_col = "gear")

Is there a way to add easy grouping like this to omni table function? Or have another function for grouped tables? 
I noticed that if you pass a grouped df to gt() it assumes you want to use the group_by() cols to group the table as well. 
Just seeing if this easy to add, thanks!

<sub>[R-32](https://linear.app/rfortherestofus/issue/R-32/group-col-to-omni-table)</sub>

**Comment by dgkeyes** [comment]
We can definitely look into adding this. In some ways, using `gt` would be easier. The only issue with `gt` is that it doesn't work within Word, which is why we use `flextable` instead. I bet @tvroylandt will have some ideas here.

**Comment by OskaratOmni** [comment]
That's a good point, @dgkeyes . In the moment I was thinking only of that slidsy presentation that I was revamping using the OMNI template. For going to word we probably would need to handle grouped tables in a different way. Perhaps that means only having grouped tables in html outputs or it could mean formatting the table object before passing it to omni_table(). I'm open to suggestions. thanks!

**Comment by tvroylandt** [comment]
![image](https://github.com/rfortherestofus/omni/assets/28248895/aa9e2288-84f4-45e6-8af9-c4ae0d222586)

Here is an example table made with `gt`. I added an `option` parameter to the `omni_table` function so that you can choose if you want it with `gt` or with `flextable` (which is the default).

It works with Word too but not with the full formatting

**Comment by dgkeyes** [comment]
@tvroylandt just so you know, I don't think the `as_word()` function works for any formatting, which makes it basically unusable in Word.

**Comment by OskaratOmni** [comment]
hey @tvroylandt, this table function is working great. 
One thing I've noticed is that the default behavior is to shade the first column a darker color. This is great when that first row is an ID or a category and the rest are variables. But sometimes we might not want the first column to have a different color. Is there a way to add an option to turn 'off' the dark blue first column when it isn't needed? Thanks!

**Comment by tvroylandt** [comment]
@OskaratOmni I added a `first_col_blue` parameter in the function. This is TRUE by default but could be set to FALSE to avoid having the first column as blue

**Comment by dgkeyes** [comment]
@OskaratOmni just want to see if you have any questions on this before we close the issue.

**Comment by OskaratOmni** [comment]
It's working great. Yes fine to close, thanks @tvroylandt  and @dgkeyes
