### ISSUE TITLE
OMNI logo in slidy template

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#29]
Hey @tvroylandt and @dgkeyes 
I working with the slidy template I noticed that the logo isn't showing when I knit. 
I think the issue might be in the url for the images, e.g. something like: 
background-image: url(../../../../assets/omni_rmd_template/images/colorbar.svg);

Is that assuming a certain location for the particular brand asset in the folder tree? 

Perhaps I am wrong about that but the logo isn't showing when I knit the file and there are the following warnings in the render:
[WARNING] Could not fetch resource ../../../../assets/omni_rmd_template/images/colorbar.svg
[WARNING] Could not fetch resource ../../../../assets/omni_rmd_template/images/colorbar.svg
[WARNING] Could not fetch resource ../../../../assets/logo/OMNI_Logo-Gold_Stacked.svg

<sub>[R-33](https://linear.app/rfortherestofus/issue/R-33/omni-logo-in-slidy-template)</sub>

**Comment by OskaratOmni** [comment]
I see, thanks Thomas,
I was indeed using it inside of a project folder.

**Comment by tvroylandt** [comment]
I just wrapped the slidy template into a function : `omni::omni_slidy`

**Comment by dgkeyes** [comment]
Looks like this is finished so I'm going to close it. @OskaratOmni feel free to re-open if you need us to do anything else.
