### ISSUE TITLE
[R-36] Add function to get long variable names from Qualtrics

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#30]
From email discussion: 

> Here's what Thomas and I will do: create a function that will create a data frame that has both long and short names from a Qualtrics survey. We can also then create a function that replaces short names with long names (and vice versa if you'd like) using this data frame.

<sub>[R-36](https://linear.app/rfortherestofus/issue/R-36/add-function-to-get-long-variable-names-from-qualtrics)</sub>

**Comment by tvroylandt** [comment]
I added two functions for that :

- `qualtrics_get_labels` will output a dataframe with short and long names
-  `qualtrics_apply_labels` will take the result of the previous function, a dataframe from `qualtrics_get_survey` (either the whole or a subset, it can be one column and you can add new ones that won't be renamed) and rename everything from short to long

The `add_var_labels` parameter from `qualtRics::fetch_survey()` doesn't seem to be working thought

**Comment by dgkeyes** [comment]
@OskaratOmni 👆

**Comment by dgkeyes** [comment]
@OskaratOmni if it's helpful, I can record a video showing how this works (which we can also add to the documentation). To do that, I'd need you to give me the id for a survey so I can pull it down.

**Comment by OskaratOmni** [comment]
I have used it and it works great, thanks @dgkeyes . Sorry for slow response.

**Comment by dgkeyes** [comment]
Great! I'll close the issue now.
