### ISSUE TITLE
Create data cleaning/checking guide

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#35]
null

<sub>[R-37](https://linear.app/rfortherestofus/issue/R-37/create-data-cleaningchecking-guide)</sub>

**Comment by OskaratOmni** [comment]
Hey David, so we have two different tools with pretty similar names. The data cleaning guide and the data checking guide are actually different. I think perhaps we should rename 'data checking' to 'syntax checking' because the emphasis is on quality and accuracy of the code - but this is of course measured in part by evaluating if the results of the syntax produce accurate data... Anyway, more on that later but just so you know.

**Comment by OskaratOmni** [comment]
I just added you and @tvroylandt as collaborators on an OMNI project called 'guides and tutorials.' 
There will be more rmd and .r files added to this shortly. For now, please see just 'data_checking.rmd' 

https://github.com/OMNI-Institute-QuantBPT/guides-and-tutorials

Let me know if you need more explanation for the difference between 'on the go' and 'formal' checks. 
The formal checks section is not well developed. These would include the kind of data check that @tvroylandt helped with a couple weeks ago on the census data. 

Also, please think of things that you do yourselves when coding or reviewing code - any tips welcome. 

The target audience here is someone who has completed David's onboarding course and shown that they have some R capacity. This kind of person is still very much a beginner but we aren't going to go to square 1... if that makes sense. 

Anyway, let me know what you think. thanks!

**Comment by tvroylandt** [comment]
Thanks @OskaratOmni.  This is a great document (but very dense) ! 

I put my changes on your commit : https://github.com/OMNI-Institute-QuantBPT/guides-and-tutorials/commit/556845de599eb309e2538d3c3f57d26a147e1739

I also added some little changes on this file directly that you can see here (mostly typos) : https://github.com/OMNI-Institute-QuantBPT/guides-and-tutorials/commit/6485aac7e94dc46a8868fdba33aee6ef862c95ed


**I will read it again another day and make additions (especially in the formal checks sections) and other comments.**



Just to say, for future checks, you could create a branch and a pull request with your file. Doing this will allow us to comment directly on the pull request and you can answer there. It's a great tool for collaboration and commenting on code and documents.

**Comment by dgkeyes** [comment]
And if you'd like help doing pull requests, just let me know. I can walk you through it.

**Comment by OskaratOmni** [comment]
Thanks @dgkeyes , I have done pull requests before but not for quite this situation so I could certainly use a little more guidance.

**Comment by OskaratOmni** [comment]
Thanks for the review @tvroylandt ! I think we have a lot to think about. I want it to be not so dense by the time we are sharing it with novice R users.

**Comment by OskaratOmni** [comment]
Hey @tvroylandt  and @dgkeyes, 
I added a quick example of using assertR. I haven't added add much text and guidance around it yet. That needs to be added or it won't make sense. But I wanted to talk with you about how I struggle with the usefulness of assertR. It seems like we are thinking of the next programmer to come to the script after us. We have all these variables and if the next person makes a mistake in the coding, then using assert(in_set(...)) could catch it. However, the use of in_set seems quite limited. Note that in the example I added, there is a variable called 'fips'. I want to make sure, using assertR, that there is an exact match between the variable 'fips' in the dataset and the vector called to assert(in_set()) called 'right_fips', but if I make changes to right_fips to include wrong entries, it won't flag those errors.  Or at least I don't know how to. So I find that I am always wishing for a little more functionality with assertR and maybe feeling that custom data checks (like one Thomas helped with a few weeks ago) are more useful. I would love to hear about ways to use assertr more effectively though.

**Comment by tvroylandt** [comment]
@OskaratOmni 

`assertR` is great in a pipeline when you need to be sure that you have the right variables, with the right values.

What is difficult, I agree, is that it's more like testing functions, you need to explicitely specify an output goal.
In this package the `right_fips` is supposed to be always right. That's the point, you need to setup a truth somewhere so that the computer know what to compare.

**Comment by dgkeyes** [comment]
[This guide](https://cghlewis.com/blog/data_clean_01/) written by Crystal Lewis might be worth including.

**Comment by OskaratOmni** [comment]
That looks great @dgkeyes, thanks! I have quickly perused Crystal's book but not seen that before. I think there's a lot we could borrow from it.
