### ISSUE TITLE
Share data viz guide docs

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#36]
This will allow us to get started on #34

<sub>[R-40](https://linear.app/rfortherestofus/issue/R-40/share-data-viz-guide-docs)</sub>

**Comment by OskaratOmni** [comment]
First, the 'one pager' guide that i asked our data viz folks to make, capturing the main guidance in one place: 
[OMNI Data Viz Specs for R Template.docx](https://github.com/rfortherestofus/omni/files/12851134/OMNI.Data.Viz.Specs.for.R.Template.docx)

Second, a doc about philosophy of data viz and associated checklist: 
[OMNI Data Viz Philosophy and Checklist.docx](https://github.com/rfortherestofus/omni/files/12851142/OMNI.Data.Viz.Philosophy.and.Checklist.docx)

**Comment by OskaratOmni** [comment]
I took a longer look at the ggplot gallery this morning and it is not as far along as I'd hoped. I'm not sure what to do about this because I want to get a draft to you soon. I might schedule a meeting with David to talk about it. 

In the meantime, here is another resource. This pdf is made from a confluence page that lists examples of OMNI data viz. 
[DVBP-Data Viz Examples (Graphs and Charts)-101023-144623.pdf](https://github.com/rfortherestofus/omni/files/12859154/DVBP-Data.Viz.Examples.Graphs.and.Charts.-101023-144623.pdf)

**Comment by dgkeyes** [comment]
Happy to chat about this. Feel free to schedule a call if you'd like.

**Comment by dgkeyes** [comment]
Just FYI @tvroylandt and @OskaratOmni I was trying out an app to sync GitHub issues to a thing called Linear I'm testing for project management. That's why the issue titles all got changed. Nothing should be broken.

**Comment by dgkeyes** [comment]
Hi @OskaratOmni just wanted to check in to see if you have any udpates on getting us a revised data viz guide. Would love to move this forward!

**Comment by OskaratOmni** [comment]
Hey @dgkeyes , the three documents above are all we have at the moment. Is there anything that is clearly missing from them that we can add or edit? They can all be thought of as drafts, of course. I think the main one to consider is the 'OMNI Data Viz Specs for one pager'. Let me know what you think and/or what info isn't in there.

**Comment by OskaratOmni** [comment]
Also, just to make sure we aren't using slightly different terms... the other matter is a draft of the gallery itself, which I haven't been able to send you yet. To me, that is different than the 'data viz guide', which informs the content of the gallery.

**Comment by OskaratOmni** [comment]
hey David, I think its a draft of the gallery itself. That is what I'd wanted to send you a few weeks back. I'm not sure if it would be a good use of time or not, but perhaps reviewing those docs above, along with what you already know about OMNI data viz, could be useful if it helps identify any 'gaps' - like important guidelines in the data viz that are ambiguous or unspecified? If that doesn't seem useful I understand.

**Comment by dgkeyes** [comment]
Ok, no worries. I'm going to work on this soon and will let you know if I have any questions. Whenever you do have any updates on the gallery, just let me know, but I'll be working on creating the version that will live within the package.

**Comment by OskaratOmni** [comment]
hey David, I think it's a draft of the gallery itself. That is what I'd wanted to send you a few weeks back. I'm not sure if it would be a good use of time or not, but perhaps reviewing those docs above, along with what you already know about OMNI data viz, could be helpful if it helps identify any 'gaps' - like important guidelines in the data viz that are ambiguous or unspecified? If that doesn't seem useful, I understand.
