### ISSUE TITLE
add caption to omni_table

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#38]
Hey @tvroylandt  and @dgkeyes , how can I add a caption to the omni_table()? It would be nice if doing this led to automatic table numbering as with using caption argument with kable(). If that's not possible, or is a pain to add, with flextable then just let me know and we can work around.

**Comment by dgkeyes** [comment]
Could you use the [`set_caption()` function](https://davidgohel.github.io/flextable/reference/set_caption.html) from `flextable`? It looks like you can use the `tab.cap` code chunk option in RMarkdown (see [here](https://davidgohel.github.io/flextable/reference/set_caption.html#r-markdown)).

**Comment by dgkeyes** [comment]
@OskaratOmni just wanted to check to see if this worked for you.

**Comment by OskaratOmni** [comment]
Thanks @dgkeyes , I tried it, and it works pretty well. The formatting of the table captions is perhaps just slightly off. 
However, this works for using automatic table numbering, which was main feature I wanted to capture. I think we can close it. thanks!
