### ISSUE TITLE
consolidate relevant resources to OMNI R resources repo

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#41]
Hey @dgkeyes  and @tvroylandt 
I have created a repository as a new place to put the ggplot gallery and future related resources.
I have added you both so you probably already have notifications to this effect. 
The 'issue' is to move the ggplot gallery there. 

https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources

**Comment by tvroylandt** [comment]
Thanks Oskar. No worry, I'll move that over the weekend in the new repo

**Comment by tvroylandt** [comment]
I'm closing this one (plus https://github.com/rfortherestofus/omni/issues/34, https://github.com/rfortherestofus/omni/issues/35, https://github.com/rfortherestofus/omni/issues/33, https://github.com/rfortherestofus/omni/issues/32) in favor of more detailed issues in https://github.com/OMNI-Institute-QuantBPT
