### ISSUE TITLE
add grouping to omni_table()?

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#43]
Hey @tvroylandt  and @dgkeyes ,
Just before the recent upgrades to omni_table() I had gotten into the habit of using gt and gtExtras. 
One nice thing about that is the ease with which you can do 'grouped' tables. 

Is there a way to add that functionality (and that ease) to omni_table()? 

What I mean is being able to do the following to have one variable subset the table into groups: 

library(tidyverse)
library(gt)
library(gtExtras)

my_tab = function(data, my_caption,...){
  data %>%
     gt(caption = my_caption) %>%
    gt_theme_pff()
} 

data = as_tibble(iris) %>% sample_n(40)
my_tab(data, my_caption = "cool flowers")

my_tab(data %>% group_by(Species), my_caption = "cool grouped flowers")

**Comment by OskaratOmni** [comment]
I kept playing with it and this gets pretty close: 

omni_table(data %>% group_by(Species), option = "gt")

**Comment by dgkeyes** [comment]
> I kept playing with it and this gets pretty close:
> omni_table(data %>% group_by(Species), option = "gt")

Is there anything in that code that doesn't work as you want it to? In other words, anything we need to fix to make it work for you?

**Comment by OskaratOmni** [comment]
Well, I guess a few questions - 
First, is this how you would do it? Is there another way? 

Is it the case that gt only works with html output? (I *think* so but haven't yet verified). 
A colleague tried the above code knitting to pdf using one of our OMNI templates and the above code didn't work for that.

**Comment by OskaratOmni** [comment]
I have gotten a little bit further. 
I think its the case that we can't use 'as_flextable()' with the omni package, right? From your course, David, I saw that as_flextable instead of flextable gives different options for how the grouping variable looks in a table like this: 

data = as_tibble(iris) %>% sample_n(40)

data |>
  as_grouped_data("Species") |>
omni_table(first_col_blue = FALSE) |> 
  set_header_labels(Sepal.Length = "Length",
                    Sepal.Width = "Width", 
                    Petal.Length = "Length",
                    Petal.Width = "Width") |> 
  add_header_row(
    values = c("Sepal", "Petal", ""),
    colwidths = c(2,2,1)
  ) |>
  add_header_lines(
    values = c("Title", "Subtitle")) |>
  align(j = "Species", part = "body", align = "left") |>
  align(j = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"), 
        part = "body", align = "right") |>
  autofit()

**Comment by dgkeyes** [comment]
Yes, so `flextable` is the only option that works with Word. If you're knitting to Word, you definitely need to use `flextable`. In terms of `as_flextable()`, which video/course are you referring to? 

I've never done any of the grouping with tables so you may be further along in your knowledge here than I am.

**Comment by OskaratOmni** [comment]
I learned about as_flextable() in 'use groups instead of repetitive columns' which is the forth, I think, lesson in making beautiful tables with R. 

You can see the difference in how it aligns the grouping variable here: 

data |>
  mutate(Species = str_to_title(Species)) |>
  as_grouped_data("Species") |>
 # omni_table(first_col_blue = FALSE) |> 
 # as_flextable(hide_grouplabel = TRUE) |>
  as_flextable() |>
  set_header_labels(Sepal.Length = "Length",
                    Sepal.Width = "Width", 
                    Petal.Length = "Length",
                    Petal.Width = "Width") |> 
  add_header_row(
    values = c("Sepal", "Petal"),
    colwidths = c(2,2)
  ) |>
  add_header_lines(
    values = c("Title", "Subtitle")) |>
  align(i = 3, align = 'center', part = 'header') |>
  align(i = c(1,2), align = 'left', part = 'header') |>
  autofit()

**Comment by tvroylandt** [comment]
Hi,`omni` use `flextable` instead of `as_flextable` behind the scene. But this should works :

```
as_tibble(iris) |> 
  sample_n(40) |>
  mutate(Species = str_to_title(Species)) |>
  arrange(Species) |>
  as_grouped_data("Species") |>
  omni_table(first_col_blue = FALSE)
  ```

**Comment by OskaratOmni** [comment]
Thanks @tvroylandt , I ended up doing something very similar to this. Note that with 'as_flextable' it treats the placement of the grouping column a little differently. It isn't a huge issue but by removing the extra spaces it makes for a nicer look. Compare what you just shared to: 

```
as_tibble(iris) |> 
  sample_n(40) |>
  mutate(Species = str_to_title(Species)) |>
  arrange(Species) |>
  as_grouped_data("Species") |>
  as_flextable(hide_grouplabel = TRUE)
```

**Comment by tvroylandt** [comment]
I see. We could think about adding an if/else case in the function to handle that case. Would that fit ?

**Comment by OskaratOmni** [comment]
Yes that would work. We aren't too picky. I would even be okay with a second function that is omni_table_grouped or something like that. But modifying omni_table with a simple additional argument is probably better. Maybe there is an option for grouped = that is usually grouped = NULL and the function behaves as it does now unless you specify a column name to grouped? Whatever you think is best works for us tho

**Comment by OskaratOmni** [comment]
@tvroylandt , this is great, thank you. 

We talked it over a little and I wonder if it would be possible to change the shading of the grouping row. 

In the example code you sent above:
```
as_tibble(iris) |> 
  sample_n(40) |>
  mutate(Species = str_to_title(Species)) |>
  arrange(Species) |> 
  omni_table(grouped = "Species")
```
The rows with grouping variables are blue with white font, as is the first row. I think it is clear why this is, as the arguments on shading are applying to the rows of the dataframe we pass to flextable (or as_flextable). 

For contract, please compare to: 
```
as_tibble(iris) |> 
    sample_n(40) |>
    mutate(Species = str_to_title(Species)) |>
    arrange(Species) |> 
    omni_table(grouped = "Species", first_col_blue = FALSE)
```
Where we lose the emphasis of the darker color on the rows with the grouping variables. Also, because the shading is 'every other row', it can be that shading of the grouping variables isn't consistent across the table. 

I am not sure of the difficulty, but would it be possible to make it so that the rows with grouping variables have the 'header' style of dark blue with white font? If this seems too annoying to add to the function then let me know and we can reconsider. It seems nicer when the grouping rows are like headers, do you agree?

**Comment by tvroylandt** [comment]
Ok, I did that

**Comment by OskaratOmni** [comment]
@tvroylandt  I experimented with this and unfortunately I am getting an error for any grouped table. 

`> as_tibble(iris) |> 
+   sample_n(40) |>
+   mutate(Species = str_to_title(Species)) |>
+   arrange(Species) |> 
+   omni_table(grouped = "Species", first_col_blue = FALSE)
Error in `mutate()`:
ℹ In argument: `rowid = .data$rowid + .data$rowid2 - 1`.
Caused by error in `.data$rowid`:
! Column `rowid` not found in `.data`.`

**Comment by tvroylandt** [comment]
Ooops, I forgot one line in my copy/pasting. Should be better now

**Comment by OskaratOmni** [comment]
Working now, thanks @tvroylandt
