### ISSUE TITLE
Add new version of internal simple template

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#44]
Hey @dgkeyes  and @tvroylandt 
I have made a new version of the template that we call 'internal simple' in the OMNI R package. 

It gives more instruction than the previous because we need to keep in mind some users might be quite new to R. 

If you have any comments, concerns, suggestions for the template of course just let me know. 
thanks!

**Comment by OskaratOmni** [comment]
Hmm, for some reason it is not allowing me to attach the .rmd file. I could be mistaken but I could swear that I attached one to an issue before.

**Comment by dgkeyes** [comment]
Hmm, I'm not sure. You should be able to just paste the code in a code block.

**Comment by OskaratOmni** [comment]
Seems odd that an .rmd wouldn't be a supported file type doesn't it? The layout of the issue page did change just a little bit so I wonder if its just an oversight.

**Comment by dgkeyes** [comment]
Yeah, a bit odd. In any case, just do three back ticks to start and end your code chunk and put your .Rmd code below and it should work.

**Comment by OskaratOmni** [comment]
Is it okay if I just push it and link to it? 

https://github.com/OMNI-Institute-QuantBPT/guides-and-tutorials/blob/main/possible_template_internal_reporting.rmd

**Comment by dgkeyes** [comment]
Yup, this works!

**Comment by dgkeyes** [comment]
@tvroylandt can you please review this whenever you have a chance? Definitely don't do this at the hospital or anything like that!

**Comment by OskaratOmni** [comment]
> @tvroylandt can you please review this whenever you have a chance? Definitely don't do this at the hospital or anything like that!

I 100% agree!
