### ISSUE TITLE
html report with OMNI formatting

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#45]
Hey guys, 
Another feature request but first I am just seeing how difficult this would be. 
(David, if this already exists and I am just not realizing please forgive me but let me know) 

What if we had an html style report that was formatted for sharing with clients? This means it would have some of the same formatting that is in the pdf and Word versions of our templates. Headers that are OMNI blue and perhaps an OMNI logo at the top. 
It would not have to match exactly, especially with cover page aesthetics, but something that is html and in the ballpark of the same formatting of those other templates could be handy. 

What do you think?

**Comment by dgkeyes** [comment]
No, this doesn't exist. We can work on mocking this up soonish.

**Comment by tvroylandt** [comment]
How would you share it with clients ? It's difficult to send HTML files by mail so I guess this would be done using Github Pages or Netlify ? In that case, you should get a plan for either one or another to keep it private.

**Comment by OskaratOmni** [comment]
Great question @tvroylandt , I have used github pages a couple of times. Both times I created a new repository just for the shared html so I could keep the rest of the repository private. I have made html files small enough to email but that usually feels a little cumbersome. I think we can also create a shared link directly to the html file in dropbox.

**Comment by OskaratOmni** [comment]
It depends on the project. Some of our reports that we do in pdf we post on our website when the project is done, so they can be public. I just got a 'public good' account with Netifly so that has same features as their 'pro' version but is free for nonprofits. I haven't tried it yet but it seems you can password protect your links with this account, so we could do that if needed.

**Comment by tvroylandt** [comment]
Great. It may be worth to have a roadmap on how to push to Netlify in both cases

**Comment by dgkeyes** [comment]
@OskaratOmni do you want us to add something in the OMNI R Resources guide about publishing to Netlify?

**Comment by OskaratOmni** [comment]
I don't think so, thanks! It seems pretty straight forward. 

Let's table that question and revisit once we are using Netifly more. Maybe there are some tips and tricks or some features we don't know about but in terms of just getting a link to a document it is really easy to use.

**Comment by dgkeyes** [comment]
Ok, sounds good!

**Comment by tvroylandt** [comment]
On this one, I created a sample template with logo and header in blue background. We can then improve it

**Comment by OskaratOmni** [comment]
@tvroylandt  we just played with this one in the last couple of days and it has gone really well. I think it looks really nice. 

Let's please keep it open in case there is some more feedback in the next week.

**Comment by tvroylandt** [comment]
@OskaratOmni  have you had time to play with it ? Is everything ok ?

**Comment by OskaratOmni** [comment]
Yes! It looks really nice, thank you. 
At some point I might update the guidance text at the top of the document but this is great for now.
