### ISSUE TITLE
 ggplot2 theme - show.legend defaults to TRUE, should probably be default to FALSE

### ISSUE THREAD

**Issue by LibbyHeeren** [rfortherestofus/omni#47]
In the OMNI Data Viz Specs Template document, it says **"Data should be labeled directly, avoid legends. Position data labels near the data rather than in a separate legend (e.g., on top of or next to bars and next to lines)."** I noticed in the `theme.R` file the `theme_omni()` default is to have `show_legend = TRUE` so we might want to consider having it default to FALSE.

**Comment by LibbyHeeren** [comment]
(There is an argument for leaving it TRUE and asking users to almost always change it to FALSE themselves, which is to avoid confusion when someone actually does need the legend and can't avoid it)

**Comment by tvroylandt** [comment]
Closed by #48
