### ISSUE TITLE
Create functions to set defaults (e.g. font family) on geoms and restore them to defaults

### ISSUE THREAD

**Issue by dgkeyes** [rfortherestofus/omni#49]
See discussion in #48

**Comment by tvroylandt** [comment]
@LibbyHeeren , feel also free if you want to try this one. Otherwise I'll just do it

**Comment by LibbyHeeren** [comment]
@tvroylandt, I think I better focus on the omni resources site for right now. 

@dgkeyes, will I need to update all of the plots and the guidelines to include the use of changing text defaults instead of setting the font family and size inside of `geom_text`?

**Comment by dgkeyes** [comment]
> @dgkeyes, will I need to update all of the plots and the guidelines to include the use of changing text defaults instead of setting the font family and size inside of geom_text?

Yes, we will need to update that. Don't worry about it for now. We can come back to it later on.

**Comment by tvroylandt** [comment]
This should be good @LibbyHeeren 

Just use `set_omni_defaults`/`ggplot_defaults` to setup/unsetup defaults
