### ISSUE TITLE
Revamping the OMNI pdf template

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#50]
Hey @dgkeyes , 
We were just look at the one of the templates in the OMNI package called OMNI RMarkdown template. This seems like it was built for a particular report. I have not used it before today. 
One of our team members was trying to use and had a hard time making simple edits - like removing the cover page and adding page numbers. The css files are in the package files so they are kind of hard to edit. I'm not sure how we would with this setup. 

So I have a few thoughts on resolution. One is to have two different pdf templates. One that is for reports (the 'OMNI RMarkdown Template' with a few modifications). The second is maybe called 'memo' and would have no cover page at all, just formatted headers. 
Both of them should have page numbers though. 

The question is how to make them editable? 
Should the css files download to a folder called 'css' each time the template is loaded so they can be customized to fit a particular deliverable? Is there another way? 

Thanks!

**Comment by OskaratOmni** [comment]
Oh that sounds interesting and promising but I am not familiar with it at all. 
Can we please try this fairly soon? I think some on our team would use it right away.

**Comment by tvroylandt** [comment]
That's more or less the principles of the `pagedreport` package we wrote with David : https://github.com/rfortherestofus/pagedreport

I'm on my way to do a revamping of this package too, on Quarto instead of Rmd and that's what I use.
Should be ready for the beginning of the year (not having the option to do a good sleep at night makes it difficult to work long hours on the day unfortunately)

Changing colors and such things isn't too complicated. It's more difficult when we have to deal with margins and so on.

**Comment by OskaratOmni** [comment]
For our needs we are fine with just a simple template. I think that the 'memo version' would get more use. I could find an example of what I mean if that would be helpful.

**Comment by dgkeyes** [comment]
Sounds like this is a good plan! Just for context, I believe there are two templates because someone on your team (I don't remember who) wanted to add another one. Does that sound familiar to you @OskaratOmni?

**Comment by OskaratOmni** [comment]
Hey David, are there two now? I thought we only had one to pdf, but I could be mistaken. We might want to think about a few context-specific ones tho

**Comment by OskaratOmni** [comment]
David you were right, there are two already! Sorry, if it seems weird I didn't know that its bc I actually haven't done much in pdf in a long time, lol.

**Comment by dgkeyes** [comment]
Ok, just let us know which one you want us to keep.

**Comment by OskaratOmni** [comment]
David, we would like two (or potentially more) pdf templates, one for a report and one for a memo. We don't have a 'memo' style one yet. A memo would not have a cover page at all but just start with the level one header at the top of the first page.

**Comment by tvroylandt** [comment]
As you can see, I also really simplified the CSS file

**Comment by tvroylandt** [comment]
On my side, this one is ok.

**Comment by OskaratOmni** [comment]
@tvroylandt , thanks for making a draft of the pdf memo. I made a few changes but I messed up the pull request. I hope you can see the rmd and associated pdf here? 
https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources/tree/datacleaning_obupdates/pdf%20memo%20template

Basically I am making it more of a general template and adding more of the OMNI defaults.

**Comment by OskaratOmni** [comment]
One thing I couldn't figure out is that in the knitted pdf the gridlines in the table are white instead of black. Can you please make them black?

**Comment by tvroylandt** [comment]
@OskaratOmni thanks for the feedback. FYI, I created the report in this repo (please see https://github.com/rfortherestofus/omni/blob/main/inst/assets/omni_pdf_memo.css). I'll work on that soon to adapt to your changes and for the tables.

**Comment by tvroylandt** [comment]
@OskaratOmni I tried to put this in the new format but I'm unsure to have everything since I've deeply changed the original CSS). Please tell me if that's ok for you.

**Comment by tvroylandt** [comment]
@OskaratOmni just a quick update on this one, is everything ok ?

**Comment by OskaratOmni** [comment]
Thanks for checking @tvroylandt  - 
My intention is to change the text in the pdf memo version - I thought I did that already but I cannot find it now. 
I will update that and send and updated version soon. Let's please keep open for now.

**Comment by OskaratOmni** [comment]
@tvroylandt   - I looked at the pdf memo version and I am not sure if the edits you made above were pushed? 
The header color is still red and those changes linked in the comment above (I just added eyes to it) don't seem to be there. 
Am I misunderstanding something on my end? Sorry if so.

**Comment by dgkeyes** [comment]
@OskaratOmni just to make sure, did you reinstall the package?

**Comment by OskaratOmni** [comment]
This memo still needs to be updated. I think @tvroylandt  said he worked on the css as well. 
The version that is in the project, and shown in the video, is quite out of date - you can see I sent a new version back on December 14th and after that Thomas had made those changes and worked on the css file.

**Comment by OskaratOmni** [comment]
Here's the rmd in case you didn't see the link above:

**Comment by tvroylandt** [comment]
![skeleton](https://github.com/rfortherestofus/omni/assets/28248895/5ac6e1a1-6b0f-41e8-9e82-95daf2af948c)

**Comment by OskaratOmni** [comment]
Yes - this seems to be working perfectly, thanks!
