### ISSUE TITLE
page numbering on word and pdf templates

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#56]
Hey @tvroylandt  can you please add page numbering to our word and pdf templates? 

I considered requesting that this be a parameter but I think we will always want page numbers after the first page or cover page. 
Can you please add that?

**Comment by tvroylandt** [comment]
Ok.

For the PDF one, the numbering start at 1 on page 2, is that ok ?

**Comment by tvroylandt** [comment]
@OskaratOmni just a quick update on this one, is everything ok ?

**Comment by OskaratOmni** [comment]
Yes, the page numbering seems to work, thanks!
