### ISSUE TITLE
ggplot gallery 1: Vertical bars are okay

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#57]
Howdy y'all! Happy new year! 
Our first issue of 2024 is a pretty easy one. 

In the guidelines section of the gallery it says: 

"If you’re creating a bar graph, for instance, try to create it horizontally, with groups on the y-axis and values on the x-axis, so that the bar labels can be read horizontally." 

We actually don't mind vertical bar graphs. Granted, it is definitely the case that if you want horizontal text that the horizontal bars will often make it easier to have legible and clear horizontal labels. But if the labels are short, vertical bars can work fine. The main thing is to avoid vertical or slanted labels. 

A simple rephrase to emphasize the importance of horizontal labels without giving the impression that horizontal bars are strongly preferred would do the trick. (Perhaps making it clear that horizontal bars help with longer or complex labels)

**Comment by dgkeyes** [comment]
I changed the paragraph to say:

> If you're creating a bar graph, for instance, try to create it horizontally, with groups on the y-axis and values on the x-axis, so that the bar labels can be read horizontally. However, if the labels are short enough, it is fine to use vertical bars. Most of all, we want to avoid vertical or slanted labels.

How is that @OskaratOmni?

**Comment by OskaratOmni** [comment]
That
s great, thanks @dgkeyes
