### ISSUE TITLE
ggplot gallery 2: ordering groups 

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#58]
Under horizontal bar graph - 
In our current text we have: 
"leave the groups ordered alphabetically since they’re human categories", which is generally true. However if there are categories like 'unknown' we tend to put those at the bottom. If it is easy to explain how to do that, it would be a helpful addition. 

Here is the full comment from Julia, one of our experts in data viz and reporting: 

"The only exception to this I'd make is that I'd typically move unknown/not answered groups to the end. I don't know that there is a way for you to build that into the code, since those groups can vary a bit in name/context. Just thought I'd mention in case you can think of a way to do that, or maybe we just add some contextual info on that to the guide so people are prompted to do it themselves (and know how) if it comes up."

**Comment by dgkeyes** [comment]
Fixed in https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources/commit/0e9b8fe155c577d1bb19d58f78667a5fcd6d1005

**Comment by dgkeyes** [comment]
Just FYI, @OskaratOmni, I set it to manually move "Prefer not to answer" to the end, but if you want to come up with a more elegant solution that takes various options for this NA category, we can do that.

**Comment by dgkeyes** [comment]
Also, I'm publishing my changes to a [new location](https://quiet-choux-dfc60e.netlify.app/ggplot/graph_horizontal_bar_chart) so that we don't mess up the comments left on the other site. We can determine the best place for the final version to live later.
