### ISSUE TITLE
ggplot gallery 3: lingering 0 on axis label 

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#59]
On horizontal bar graph, under "Graph" it says: 

"remove x and y-axis labels"

In the sample image there is an extra 0 at the bottom

**Comment by dgkeyes** [comment]
Fixed in https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources/commit/0e9b8fe155c577d1bb19d58f78667a5fcd6d1005
