### ISSUE TITLE
ggplot gallery 4: edits to single bar graph

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#60]
Our reviewer had some requested edits to the graph itself - 
I am not on this project so don't have a lot of context about what the graph is tracking in terms of followups and the like. 

> A couple edits I'd make to this graph (partly to make it more applicable to common scenarios at OMNI and partly to adjust formatting):
> 
>      - instead of having the n's in the labels I'd have the category. So it would be like: Completed Follow-ups 28% and Incomplete Follow-ups 72%.
>      - Adjust colors of the labels so they match the segments they correspond to.
>      - Then I'd adjust the yellow bar to be a target since that's more applicable to our work except the very specific instance of GPRA tracking and might help people conceptualize when to use it. Change label to Follow-up Target 70%

**Comment by OskaratOmni** [comment]
@dgkeyes , thinking more about these suggested edits. I think the colors of the labels should match, but some might like to have the n's in the labels. 

Replacing the labels with the categories might be something that is worth showing how to do in the tutorial. So have the figure with the ns and then say "What if you wanted to change these labels to the categories,  here's what that would look like...etc" Does that make sense?

**Comment by dgkeyes** [comment]
Fixed in https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources/commit/9af1eed05f1803e50285511610787a3ed31d15c3.

@OskaratOmni please take a look [here](https://quiet-choux-dfc60e.netlify.app/ggplot/graph_single_bar_chart) and let me know what you think.

**Comment by dgkeyes** [comment]
@OskaratOmni just wanted to ping you to see if you had any thoughts on what I put together.

**Comment by OskaratOmni** [comment]
I think it looks good David, thanks!
