### ISSUE TITLE
ggplot gallery 5: stacked bar legend position 

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#61]
Regarding having legend at the bottom of the stacked bar, our reviewer commented as follows: 

"I would move the legend to the top. Some data viz best practice research shows that helps people process since they will read top-to-bottom but with the legend at the bottom they have to jump down to read it and then go back up to the top of the graph to start to interpret it."

**Comment by dgkeyes** [comment]
Fixed in https://github.com/OMNI-Institute-QuantBPT/OMNI-R-Resources/commit/e2e2ec243914be54698e2a5b671428c22774a2c8
