### ISSUE TITLE
Reporting template in Word

### ISSUE THREAD

**Issue by OskaratOmni** [rfortherestofus/omni#84]
Hey @dgkeyes  and @tvroylandt 
Can you please start on a word version of that same template that you finished for pdf last week? 

If there are certain design elements of the template that are difficult to reproduce in Word then please let me know. There is definitely some flexibility if needed. 

Let me know how goes and/or if there are any questions along the way. 

Thanks!

**Comment by tvroylandt** [comment]
Hi Oskar, what's your timeline for this one ? I don't have a lot of bandwidth of the next weeks so it may take some time to be done

**Comment by tvroylandt** [comment]
Ok, that should be fine for end of June. Thanks for your understanding

**Comment by OskaratOmni** [comment]
Hey @tvroylandt , thanks! 
That makes sense. I kind of suspected that there would be some difficulties making an exact replica of the template for Word. 
We can definitely make some compromises with the Word version and just get reasonably close. 

How do I view the init version? Did you push it to main already and I'll see it if I update the OMNI package?

**Comment by tvroylandt** [comment]
Everything is in main as `word_report_new`

**Comment by OskaratOmni** [comment]
@tvroylandt , when I experiment with this, the header doesn't show up. 
It looks like both the font and the background are reading as white, perhaps. 
I can set the background to blue inside Word and it will show up.

I know it is quite difficult to style as specifically in Word. So if we need to re-think this template, that's of course fine and we can discuss compromises that cover some but not all of the design elements in the pdf. 

Attached is what the knitted output looks like on my end. 
[new_word_test.docx](https://github.com/user-attachments/files/15906105/new_word_test.docx)
![image](https://github.com/rfortherestofus/omni/assets/106394758/d5f45bec-0a56-4b1c-b15d-d07cbd271a7d)

**Comment by tvroylandt** [comment]
The section with columns create a conflict with the title page. If you remove the two lines to create multi columns layout, this works

**Comment by tvroylandt** [comment]
I'm trying to figure out how to make both working together but I have not solution right now

**Comment by dgkeyes** [comment]
Just a quick update on this @OskaratOmni. It doesn't really seem like there is a solution here. How would you like to move forward with thinking about compromises we need to make in order to get a working version of the Word template?

**Comment by OskaratOmni** [comment]
Hey @dgkeyes , thanks for raising this. 
I am totally open to suggestions but maybe the 'easy' solution here is to drop the call-out box as an option for the Word template. 

In addition, can we please suppress warnings in the knitr options as the default? 

And can we please pass the table example using mtcars to autofit? 

Here's what my RMD looks like after making those first two edits: 

![image](https://github.com/user-attachments/assets/19dce6b0-9a4d-4783-9b66-caced77c8572)

**Comment by OskaratOmni** [comment]
When it knits, the OMNI logo is a little fuzzy looking. Is this just a function of the quality of the graphic in assets? If so I can try to find a better version.

**Comment by OskaratOmni** [comment]
When using the template, the name of the template is the same as the old one in Rstudio. 

Can we please add the suffix 'new' like in the pdf one? 
![image](https://github.com/user-attachments/assets/273ab819-b215-4283-a0a9-83993f0f5862)

**Comment by OskaratOmni** [comment]
Thanks @tvroylandt  this looks good. 

One additional thing I noticed - in the header of the document the date seems to be fixed at June 3 2024. 
I tried setting the date in the yaml the normal way, but it stayed June 3 2024
![image](https://github.com/user-attachments/assets/3cb1c09d-611e-4a94-b340-f8440d7609ab)


Is that something you can easily fix?

**Comment by OskaratOmni** [comment]
Thanks @tvroylandt  
I appreciate it. Yes that's good enough for now. 
I can imagine that there will be a few requested edits after people have tested it some more, but we can use this for sure.

**Comment by dgkeyes** [comment]
Ok, great. Closing this for now. We can reopen in the future as necessary.
